### ISSUE TITLE
Any chance you could add a run command feature?

### ISSUE THREAD

**Issue by FluffyTG** [Karashok-Leo/loot-bag#1]
A feature for the loot bags to run commands would be cool.

**Comment by Karashok-Leo** [comment]
I was wondering what you want to achieve with commands?

**Comment by FluffyTG** [comment]
> I was wondering what you want to achieve with commands?

Like let's say there's a command reward that spawns a pig at the player's feet, or maybe another creature instead of giving the player a spawn egg which would be over-powered.
