### ISSUE TITLE
[BUG] Random loot tables' display is not randomized

### ISSUE THREAD

**Issue by FluffyTG** [Karashok-Leo/loot-bag#2]
When making a random loot bag, the contents of the bag ARE randomized, however the display of the random loot table received is not randomized to match the contents.

IE, the example random loot bag will always show the zombie loot table icon instead of the skeleton or creeper.

**Comment by FluffyTG** [comment]
The icon for the incorrect loot pool is shown though, that's the issue.

**Comment by FluffyTG** [comment]
![image](https://github.com/Karashok-Leo/loot-bag/assets/139890644/e3db664e-232e-4bb8-9749-d5d12fdbccfa)![Uploading exampleRandom.gif…]()

**Comment by FluffyTG** [comment]
![exampleRandom](https://github.com/Karashok-Leo/loot-bag/assets/139890644/a04de845-4656-45d6-8a87-560cf5f3e703)

![image](https://github.com/Karashok-Leo/loot-bag/assets/139890644/6244d0fa-5745-4ca2-81bf-6276b0dfeb89)

**Comment by Karashok-Leo** [comment]
You mean that whether you immediately open the bag or wait for a moment, the icon will not scroll, but will always display rotten flesh?
If yes, provide your complete config file please (instead of screenshots).

**Comment by FluffyTG** [comment]
[loot_bag_entries.json](https://github.com/user-attachments/files/15524225/loot_bag_entries.json)
[loot_table_entries.json](https://github.com/user-attachments/files/15524226/loot_table_entries.json)

**Comment by Karashok-Leo** [comment]
![PixPin_2024-06-02_12-59-30](https://github.com/Karashok-Leo/loot-bag/assets/139102377/c7f7f95e-16bb-43e2-a0a3-4181f89d92ac)
It works fine... The icons for all candidate loots scroll in order. There's nothing wrong with that.

**Comment by FluffyTG** [comment]
Upon some more testing, when it comes to random loot bags, only the top option of the loot table is chosen as the icon and description for the contents.

![exampleRandom2](https://github.com/Karashok-Leo/loot-bag/assets/139890644/cbc9d4ac-1a9b-4133-a90e-71263cfc6047)


[loot_bag_entries.json](https://github.com/user-attachments/files/15524250/loot_bag_entries.json)
[loot_table_entries.json](https://github.com/user-attachments/files/15524251/loot_table_entries.json)

**Comment by FluffyTG** [comment]
OH, I see, maybe change the time it takes to scroll a bit more, I didn't even know it did that

**Comment by FluffyTG** [comment]
My apologies, I genuinely did not know that it auto scrolled.
