### ISSUE TITLE
Server crashes upon accessing the loot bag preview screen

### ISSUE THREAD

**Issue by SAILQAQ** [Karashok-Leo/loot-bag#3]
The server crashes upon accessing the loot bag preview screen, though this issue does not manifest in single-player mode.
**Crash Report**
[crash-2024-08-16_12.28.44-server.txt](https://github.com/user-attachments/files/16657346/crash-2024-08-16_12.28.44-server.txt)

**Comment by Karashok-Leo** [comment]
Should have been fixed in version 1.2.3
